# Generated by Django 5.2.7 on 2025-11-05 06:19

import django.core.validators
import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(default='CREATIVE EDUCATION FOUNDATION PVT. LTD', max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract')], default='part_time', max_length=20)),
                ('location', models.CharField(default='Pokhara', max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary in Rs.', max_digits=10)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], default='mid', max_length=20)),
                ('mode', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='hybrid', max_length=20)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Job requirements (one per line)')),
                ('responsibilities', models.TextField(help_text='Job responsibilities (one per line)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='applications/cvs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), pages.models.validate_cv_size])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('khalti_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('khalti_payment_token', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pages.vacancy')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('vacancy', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='khalti', max_length=50)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='pages.vacancyapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
