"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b-)z!pg-&#_)dl-q)w%pd$94hgucye4k%*ota)mw4c*8-v-vhq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'pages',
    'courses',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'courses.context_processors.user_enrollment_status',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'creative_education_db',
#         'USER': 'anish',
#         'PASSWORD': 'Anish#937',
#         'HOST': 'localhost',  # or the IP of your database server
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


# Inside the Django container its own “localhost” is itself, not your Mac.
# Docker Compose gives the MySQL container a name (db) and puts both containers on the same virtual network, so Django must use that name as the host:

# When you go back to your Mac-only project
# Just revert the settings:
# Python
# Copy
# DATABASES = {
#     'default': {
#         ...
#         'HOST': 'localhost',   # or 127.0.0.1
#         'PORT': '3306',
#     }
# }
# and shut down the Docker stack:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME', 'creative_education_db'),
        'USER': os.getenv('DATABASE_USER', 'anish'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'Anish#937'),
        'HOST': os.getenv('DATABASE_HOST', 'db'),   # <- now reads env
        'PORT': os.getenv('DATABASE_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024  # 4MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024  # 4MB



LOGIN_URL = 'login'  # This should match the name of your login URL pattern
LOGIN_REDIRECT_URL = 'home'  # This should match the name of the URL you want to redirect to after login


# Add these to your Django settings.py

# Khalti Payment Gateway Configuration
# KHALTI_PUBLIC_KEY = 'your_khalti_public_key_here'  # Get from Khalti Dashboard
# KHALTI_SECRET_KEY = 'your_khalti_secret_key_here'  # Get from Khalti Dashboard


# Email Configuration (for sending application confirmations)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'subedianish937@gmail.com'
EMAIL_HOST_PASSWORD = 'Anish#937'
DEFAULT_FROM_EMAIL = 'Creative Education Foundation <noreply@creativeeducation.com>'

# Application Fee
VACANCY_APPLICATION_FEE = 100.00  # Rs. 100

# Add 'requests' to your requirements.txt
# requests>=2.31.0

# TIME_ZONE = 'Asia/Kathmandu'