# Generated by Django 5.2.7 on 2025-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_rating_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='class_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='notified_10min',
            field=models.BooleanField(default=False),
        ),
    ]
